apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . | quote }}
  labels:
    component: app
{{ include "common-labels" . | indent 4 }}
spec:
  selector:
    component: app
{{ include "common-labels" . | indent 4 }}
  ports:
  - name: metrics
    port: 9710
    protocol: TCP
